example/index.jsx, package.json, src/PopperManager.jsx, yarn.lock
Upgrades Popper.js to latest beta + closes #3
=> upgraded to beta.3

example/index.jsx, package.json, src/Arrow.jsx, src/Manager.jsx, src/Popper.jsx, src/Target.jsx, yarn.lock
=> fix: Fixed #8

src/Popper.jsx
=> fix: Make updateState modifier return data object

src/Popper.jsx
ensures compatibility with https://github.com/FezVrasta/popper.js/pull/225
related: #20
=> fix: modifier.function is deprecated, use modifier.fn

example/index.jsx
It was re-rendering every time you click outside.
=> Changing example to be a PureComponent

package.json, react-popper.d.ts
=> add typescript definitions

package.json
for platform indepedent development
Added rimraf and cross-env 
Dependency modifications:
Added ^16.0.0 to react and react-dom peer dependencies
downgrade glamor v3 as that has been abandoned.
=> Added 16.* react peer dependency, made scripts platform independent

example/index.jsx
=> correct spelling in function name

example/animated.jsx, example/common.jsx, example/index.jsx, example/main.scss, example/modifiers.jsx, example/multiple.jsx, package.json
Refactored examples into separate components for clarity. Added an example passing custom modifiers to the Popper component and to demonstrate the out-of-boundaries hiding.
=> fix: Updated examples

.babelrc, package.json
This should fix the build issue :v:
=> fix: es5 build

src/Popper.js
=> Dodge SSR issue

package.json, yarn.lock
=> Add prop-types to dependency which is a peer of create-react-context

.flowconfig, README.md, package.json, src/Manager.js, src/Popper.js, src/Reference.js, src/__typings__/main-test.js, src/index.js, yarn.lock
These types may be useful to consumers to better type their own code.
This commit aims to get on pair with #153
=> feat: export some useful Flow types

.size-snapshot.json, package.json, rollup.config.js
Seems like I missed this case.
=> Replace process.env.NODE_ENV in umd bundles

README.md
The repo URL was incorrect, fixed now.
=> fix: update clone instructions for running locally

.babelrc, package.json
I know this is not a final solution but I think it solves this problem for now.
=> added transform-class-properties to fix issue with parcel

.size-snapshot.json, package.json, src/Popper.js, yarn.lock
This should handle the oddity in the demo site. I think this was working before, simply by accident or, result of it updating a lot. This should be sufficiently focused 👍  (I hope)
=> fix: schedule an update when placements change

package.json
=> Add dependency @types/react

package.json
=> build: remove @types/react from dependencies

.size-snapshot.json, package.json, yarn.lock
`create-react-context@0.3.0` is MIT again https://github.com/jamiebuilds/create-react-context/blob/master/package.json#L9.
The related commit is https://github.com/FezVrasta/react-popper/commit/5c423ed2ee9d51511395cbbad734156d02541cbb.
=> Upgrade create-react-context to 0.3.0

.size-snapshot.json, src/Manager.js, src/Manager.test.js
=> fix: maximum call stack size, create-react-context ref setting

README.md
Added a note to make it clear that `@popperjs/core` is needed
=> Add note about @popperjs/core

typings/react-popper.d.ts
=> added typing for RefHandler

src/usePopper.js, src/usePopper.test.js
See #393 for description
I'll see about adding a test as soon as I can. Until then anyone having this issue can just add the "position: absolute" to the arrow via their own styling
=> fix: arrow not positioned properly at initialisation #393

package.json
=> feat: Allow React 17 as peer dependency

package.json, src/usePopper.test.js, yarn.lock
- upgrade to react-test-renderer 18
- use waitFor() instead of wait(), see https://github.com/testing-library/react-hooks-testing-library/blob/01d8e509ce033dbeb7fad5f36f31f46ff7c5081c/docs/api-reference.md#wait
=> Fix react 18
