floating-ui/react-popper

- example/index.jsx
- example/main.scss
- src/Popper.jsx
Spreads modifier styles inside _getPopperStyle and updates example.
We ran into this need when working with a react custom Select component where we want the dropdown list width to match that of the trigger.  
The example includes a simpler scenario where we just change the background color.
> Spread modifier styles inside _getPopperStyle and update example

- package.json
- src/Popper.jsx
- yarn.lock
Popper.js 1.10.1 added two new options to the new `computeStyle` modifier, now the poppers can be positioned using a different offset origin (`bottom: 0` or `left: 0` instead of the usual `top` and `left`).
To make the new options work properly you have to get rid of all the manual styles computation and simply take what Popper.js provides.
> Fix needed to properly work with Popper.js 1.10.1

- src/Popper.jsx
> support top & left arrow offsets together

- src/Popper.jsx
Refs #32
Defensive PR to avoid error if `this._popper` not defined. Should inspect to understand why not defined in the first place, but really needed to fix it for my project.
Merge if it helps =)
Best
> Fix scheduleUpdate call if this._popper does not exist

- src/Popper.jsx
No support for https://popper.js.org/popper-documentation.html#modifiers..hide.
Full support for `modifiers.hide`, specifically that the `data-x-out-of-boundaries` attribute is passed along.
Passes along the `data-x-out-of-boundaries` attribute in a similar manner to `data-placement`.
We needed this in our app. More importantly, we saw no reason a wrapper around Popper shouldn’t support this.
Confirmed `build` still works. Confirmed expected example behavior when running `dev` after modifying the Popper config like so:
```js
const modifiers = {
customStyle: {
// ...unchanged
},
preventOverflow: {
boundariesElement: 'viewport',
},
hide: {
enabled: true,
},
}
```
> Fix missing data-x-out-of-boundaries attribute

- react-popper.d.ts
`popper.js`'s TypeScript definition now exports default, so it's now throwing an error when importing with `* as PopperJS from "popper.js"`. This is a small bug, but it prevents anyone using TypeScript from building their application.
> Update how react-popper.d.ts imports PopperJS

- package.json
This will allow consumers to use `react-popper` with React 16.
I didn't update the devDependency version of React 16 in this PR, although I did in my fork and everything appeared to work correctly.
> allow React 16 as a peerDependency

- react-popper.d.ts
Both `restProps` and `scheduleUpdate` properties were missing from the render function parameter type.
> Updates TypeScript definition for IPopperChildrenProps

- README.md
Thanks for this lib!
Coming message should be pretty self-explanatory :)
> Fix URL to Popper modifiers arrow documentation

- src/Popper.jsx
This fixes issues relating to `this._popper` being undefined, like #32. My personal motivation for this change is an issue where when the popper overflows the boundaries element on initial render, the position doesn't get fixed until there's a resize event.
I can create an example of this issue if you want. I can also add some tests to this PR. 
Thanks for working on this lib, by the way!
> Fix PopperJS instantiation (see issue #32)

- package.json
- src/react-popper.js
- yarn.lock
bump dev dependencies
We are back to v0.8.0 for `react-popper.js`
[react-popper.js@v0.8.0](https://unpkg.com/react-popper@0.8.0/lib/react-popper.js)
[react-popper.js@v0.8.1](https://unpkg.com/react-popper@0.8.1/lib/react-popper.js)
[react-popper.js@v0.8.2](https://unpkg.com/react-popper@0.8.2/lib/react-popper.js)
The problem was that `export Manager from './Manger'` is transformed differently than `export { Default as Manager } from './Manager'` by babel
> fix: build exports

- react-popper.d.ts
When you compile the current code with TS 2.6.2 (didn't try others, and at least with allowSyntheticDefaultImports set to false) it gives the following errors:
```
build/0/compileTypescript/0  node_modules/react-popper/react-popper.d.ts(30,27): error TS2503: Cannot find namespace 'PopperJS'.
build/0/compileTypescript/0
build/0/compileTypescript/0  30       ["data-placement"]: PopperJS.Placement;
build/0/compileTypescript/0                               ~~~~~~~~
build/0/compileTypescript/0
build/0/compileTypescript/0
build/0/compileTypescript/0  node_modules/react-popper/react-popper.d.ts(38,17): error TS2503: Cannot find namespace 'PopperJS'.
build/0/compileTypescript/0
build/0/compileTypescript/0  38     modifiers?: PopperJS.Modifiers;
build/0/compileTypescript/0 …
```
> fix for compilation error 'Cannot find namespace PopperJS'

- README.md
- example/index.jsx
- example/openable.jsx
- example/standalone.jsx
- example/standaloneObject.jsx
- example/toggleable.jsx
- src/Popper.jsx
Allows passing in a `target` prop to the Popper component directly, bypassing the need for the `Manager` and `Target` components. I implemented this feature for personal use initially, as it was needed in the development of a custom UI library.
The documentation and examples have been updated. I did try to make clear that the `Manager` and `Target` pattern is recommended and easier to use, and should be preferred in most cases.
It was challenging to think of a good example for this feature. I saw two options; get a `ref` and use that, or get an element directly from the DOM. I didn't want to do the latter, because it's generally recommended to avoid that when using React. But the `ref` was problematic as well. If I just grabbed a ref and used it right away, the resulting component would …
> Pass target directly to popper

- src/index.js
This fixes how the files gets transpiled; allowing rollup to determine the exports.
```javascript
'use strict';
Object.defineProperty(exports, "__esModule", {
value: true
});
var _Popper = require('./Popper');
Object.defineProperty(exports, 'Popper', {
enumerable: true,
get: function get() {
return _interopRequireDefault(_Popper).default;
}
});
Object.defineProperty(exports, 'placements', {
enumerable: true,
get: function get() {
return _Popper.placements;
}
});
var _Manager = require('./Manager');
Object.defineProperty(exports, 'Manager', {
enumerable: true,
get: function get() {
return _interopRequireDefault(_Manager).default;
}
});
var _Reference = require('./Reference');
Object.defineProperty(exports, 'Reference', {
enumerable: true,
get: function get() {
return …
```
> fix(build): fix cjs index exports

- .babelrc
- package.json
- yarn.lock
With this change, the `cjs` and `es` builds will refer to `babel-runtime` package to import the needed polyfills instead of inlining them on each file.
This adds `babel-runtime` as additional dependency, but I don't think we should be worried because the final size is going to be smaller than when we didn't rely on it.
Example of transpiled file before:
```
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = …
```
> perf: Use babel-plugin-transform-runtime to reduce size

- typings/react-popper.d.ts
- typings/tests/tsconfig.json
type is `undefined  | PopperJS.Placement`, not `?PopperJS.Placement` since that doesn't mean anything in typescript and was probably copied from Flow
fixes error that I get in typescript compiler:
```
node_modules/react-popper/typings/react-popper.d.ts
(24,16): JSDoc types can only be used inside documentation comments.
```
> fix placement type in PopperProps.children

- typings/react-popper.d.ts
- typings/tests/tsconfig.json
split typescript types into more interfaces that can be used separately in app code
```tsx
import * as React from "react";
import { Manager, Popper, PopperChildrenProps, Reference, RefProps } from "react-popper";
export class Component extends React.Component {
public render() {
return <Manager><Popper>{this.renderPopper}</Popper></Manager>;
}
private renderPopper = (props: PopperChildrenProps) => {
// profit! reuse the same function instance!
}
}
> more interfaces in typescript typings

- .size-snapshot.json
- package.json
- rollup.config.js
- src/Manager.js
- src/Popper.js
- src/Reference.js
- yarn.lock
UMD is important as an easy way to use library via `<script>` tag.
In this diff I added rollup with size snapshot plugin to track final
size of the library with all dependencies (except react ones).
I replaced mixed imports with `import * as React from 'react'` since
they are being semantically incorrect are failed with rollup.
> Bundle UMD with rollup

- .babelrc
- rollup.config.js
Confirmed `./lib/Manager.js` version built matches v0.10.1 and `/dist/*` matches v0.10.2
Fixes #160 
/cc @TrySound
> fix: Ensure "external-helpers" only included in Rollup builds. Fixes #1595

- .size-snapshot.json
- src/Popper.js
- src/Reference.js
- src/__snapshots__/Reference.test.js.snap
- src/utils.js
- typings/react-popper.d.ts
tested this in Blueprint's `Popover` locally (via `yarn link`) and was able to get it rendering _without_ the infinite loop!
@FezVrasta this was my first experience with Flow and I must say it was rather subpar compared to TypeScript. Why did you choose to use Flow for this project and would you consider migrating to TypeScript? (I'd be happy to do the conversion, it'll take like an hour.)
> add Popper & Reference innerRef prop

- .babelrc
- .size-snapshot.json
- package.json
`esm` is more descriptive name for distribution es modules and used by
[esm loader](https://github.com/standard-things/esm) (it's not webpack loader) and rollup [started migrating to it](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0590)
Also `es` is used in material-ui for distribution es6+ code.
> Replace es name with esm

- .size-snapshot.json
- package.json
- rollup.config.js
- yarn.lock
This diff adds size snapshot entry with esm bundle which allows to see
that some part of the code is not treeshakable.
This project is used by material-ui which provides only path imports
which looks very scary (a lot of import statement). So this project
should be treeshakable to let its users safely consumer from single
entry point and do not care about big bundle size.
> Start tracking treeshakability

- src/Popper.js
- src/Popper.test.js
- src/__snapshots__/Popper.test.js.snap
This was originally meant to try and make it harder to hit the infinite loop with refs, but ended up with a small perf improvement by reducing the need to rerender when `popper` and `arrow` nodes are set. We don't actually need to update any children until _after_ the node updates have made their way back into popper, at which point the modifier will update state and re-render with the new styles
> perf: reduce renders by moving values off of PopperState

- README.md
fixes #202 and #209 
About the warning: I'm happy to change the phrasing. Also, if you could create a wiki page linking to tooltips libs and a page listing libs using popper, we could link to those pages. (I have no rights to create wiki pages)
> doc: remove @next + clarify use

- src/Popper.js
In our codebase there's a subset of tooltips that do not work properly. Their tooltips work correctly on the first hover but on subsequent hovers only appear after you move your mouse over the element and then away from it.
After some debugging I traced the problem to the `!this.popperNode` condition inside `getPopperStyle()`; replacing it with `false` made the tooltip appear properly on all hovers. That does not seem like a proper fix, however, so I figured updating popper instance every time after popperNode updates would work, and that it does. 
As far as I understand this change results in correct behavior, since Popper instance stores a reference to the popperNode and if the node updates, so should the instance?
> Always recreate popper instance when popperNode changes

- .size-snapshot.json
- src/Popper.js
I updated `react-popper` in my project from `0.x` to latest `1.x` and found that I can't set custom `fn` for `arrow` modifier.
This PR will fix it ;-)
> Allow custom arrow modifier

- .size-snapshot.json
- package.json
This version is still API compatible. The breaking changes were a license change and internal changes.
Closes GH-226
> Allow warning 4.0

- .size-snapshot.json
- LICENSE
- package.json
- src/Manager.test.js
- src/Popper.js
- yarn.lock
Hello, first and foremost thank you so much for this library! 
This is a small non-intrusive change to how prop.referenceElement and referenceNode passed through context currently interact within the Popper.js file. 
For context, within atlassian we currently have a component that's a thin wrapper around react-popper that enforces certain internal configuration opinions. This wrapper supports both using the Reference component to instantiate a referenceNode in context; as well as the referenceElement prop of the Popper component. At the moment declaring a default value of undefined on the referenceElement prop overrides the referenceNode that may be available through context. This seems like an unintended side effect of prop spreading. 
This is a small change to ensure that if …
> More explicit referenceElement setting on Popper.js

- src/Manager.js
- src/Manager.test.js
- src/Reference.js
- src/Reference.test.js
- src/__snapshots__/Manager.test.js.snap
- src/__snapshots__/Reference.test.js.snap
`getReferenceRef` actually set the reference node and return nothing, rename it to `setReferenceNode` to avoid confusion
> refactor: getReferenceRef -> setReferenceNode to avoid confusion

- src/Reference.js
- src/Reference.test.js
#260 
With flow-typed, warning() expects its first argument to be a boolean.
Added tests to ensure warning() is called correctly.
> fix: avoid Flow error in call to warning() (#260)

- .size-snapshot.json
- .travis.yml
- package.json
- src/__snapshots__/Reference.test.js.snap
- yarn.lock
Jest 24 uses babel 7 now. As such, babel-core bridge is no longer required.
> chore: upgrade to jest@24 thus removing babel 6 dependency

- README.md
Restructures the render prop details and adds a little more about the arrow style. 
My editor also decided to correct some markdown style, which can be left out of this PR if they're not wanted.
Stems from https://github.com/FezVrasta/react-popper/issues/291
> Refactor render prop descriptions and add some detail about arrow styles

- typings/react-popper.d.ts
- typings/tests/svg-test.tsx
Re https://github.com/FezVrasta/react-popper/issues/277
Apologies to @paolostyle for scooping your PR if you still wanted to make it :sweat_smile:
> fix: update TypeScript types to allow SVG references

- typings/react-popper.d.ts
Fixes #276 
This makes the TS typings a bit easier to work with when not defining the children inline. I ran into this when using `React.useMemo` on the children, but I'm sure there are other use cases since someone else filed the issue.
> Export PopperChildrenProps and PopperArrowProps

- package.json
This sets the `package.json` field `sideEffects` to `false`. This allows for better tree shaking by downstream consumers, see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free for more information.
I skimmed over all included files and I did not see anything that would count following webpack's definition of tree shaking.
> Set side effects to 'false'

- .size-snapshot.json
- demo/index.js
- src/Popper.js
- src/utils.js
Currently if a consumer updates the `modifiers` object prop, unless another prop also changes, the new modifiers are not applied. For example, if the passed modifier `flip.enabled` were to change from `true` to `false`, the popper doesn't pick up on that fact and continues allowing the popover contents to flip.
This PR allows for the `Popper` component to construct a new popper instance with the new modifiers if and only if the `modifiers` object changes (note: this is a reference comparison and not a value comparison).
I'm not that familiar with Popper.JS so if there is a more efficient way to make sure modifier changes get propagated to the underlying popover, please let me know!
As it stands, this _could_ cause some unnecessary popper instance creation/destruction if the consumer isn't …
> Allow popper modfiers to be updated

- .size-snapshot.json
- package.json
- src/Popper.js
- yarn.lock
Popper.js' componentDidUpdate fails the props change test, which calls updatePopperInstance, which eventually causes componentDidUpdate to get called again. By using a deepEquals comparison on props.modifiers we correctly determine that the props did not update, and break the loop.
I don't have a nice simple repro for this issue, but it seems to only trigger in a complicated app on Chrome (at least 70.x->78.x) on Windows when the page's zoom level is less than 100%.
> Fix infinite loop

- README.md
When going through the `README.md` I noticed there was a missing header for the `outOfBoundaries` documentation, which made it look as it was part of `placement` documentation 🧐 💅🏻
> docs: add missing header in README

- src/Popper.js
I have a scenario where I am autofocusing an element appearing inside of a popper, and that is causing the page to scroll to the top when initially opened. A similar issue can be found here:
https://github.com/mui-org/material-ui/issues/16740
Their solution was to add `position: fixed` to the initial styles on the popper, but this library doesn't offer a way to do that. This PR makes it so that initial position style will either be `absolute` or `fixed` based on the `positionFixed` prop provided to the Popper component.
> fix: change initial position style based on positionFixed prop

- README.md
I've put the Render Props API into a collapsible element to make reading the docs easier. Hooks will be what 99% of new users will be using, and the Render Props API just adds noise. 
I've mentioned that it's a legacy API for v1.x users moving to Popper v2 and shouldn't be used in new code, and perhaps we will remove it entirely in v3. Up to @FezVrasta of course!
> docs: simplify and collapse render props into <details>

- package.json
- src/Popper.js
- typings/react-popper.d.ts
- yarn.lock
Fixes https://github.com/popperjs/react-popper/issues/351
> fix: TypeScript types broken with latest popperjs-core

- typings/react-popper.d.ts
`state` property is null for the first time
> fix: update react-popper.d.ts

- src/Popper.js
Not sure how no one has had this issue yet, but it made my code fail all over the place when upgrading from v1 to v2. The console was filled with these:
> Warning: An effect function must not return anything besides a function, which is used for clean-up. You returned null. If your effect does not require clean up, return undefined (or nothing).
I tracked it down to this effect using an implicit-return arrow function for a callback.
> Don't return a value in useEffect callback

- package.json
- yarn.lock
This PR adds React 17 ([released on October 20](https://reactjs.org/blog/2020/10/20/react-v17.html)) to the supported `peerDependencies`.
It also changes the `react` version in the `devDependencies` so the tests run against React 17.
> Add React 17 to peerDependencies

- .flowconfig
- package.json
- src/Popper.test.js
- src/RefTypes.js
- src/__typings__/main-test.js
- yarn.lock
I'm getting flow errors from `react-propper` in my `node_modules`, so I figured I'd upgrade it.
One notable thing I found is that [this file](https://github.com/popperjs/react-popper/blob/master/src/RefTypes.js#L1) doesn't actually have a flow directive so it's not being parsed by flow, and therefore everything being imported from it is `any`.
> Upgrade flow

- .size-snapshot.json
- package.json
- src/Manager.js
- yarn.lock
Addresses #405 
In short: `create-react-context` doesn't support react v17, and since it looks to be abandoned, use `@hypnosphi/create-react-context` instead.
> use @hypnosphi/create-react-context to support react 17 in v1

- src/Manager.js
I ran into an issue with react-popper v2.2.3, and I believe this is the right way to fix it. These changes have worked for me locally in my app that had previously been crashing.
The error message that React has been giving me is "Invalid hook call", although I know from previous experience that the error message is incredibly misleading and can be caused by many different issues.
https://reactjs.org/docs/error-decoder.html/?invariant=321
I believe the underlying issue is with calling `setState` (or here, `setReferenceNode`) after the component has unmounted. `setState` happens asynchronously and is therefore inappropriate inside the cleanup function for a `useEffect` hook.
I removed the other cleanup function in this PR because I believe it to no longer be necessary. It was added to …
> fix(hooks): Avoid setState in unmounted components.

- src/Reference.js
Without this, the reference is set to null for _every render_, making
it mostly unusable.
> Only set Reference's innerRef to null when unmounting
